CREATE TABLE ERA
(
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    inicio INT NOT NULL,
    fim INT NOT NULL,
);

 

CREATE TABLE DESCOBRIR
(
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    nome VARCHAR(256) NOT NULL,
);

 

CREATE TABLE LOCALIZACAO
(
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    pais VARCHAR(256) NOT NULL,
);

 

CREATE TABLE GRUPO
(
    id INTEGER NOT NULL PRIMARY KEY IDENTITY,
    nome VARCHAR(256) NOT NULL,
);

 

CREATE TABLE DINOSSAURO 
(
    id VARCHAR(20) NOT NULL PRIMARY KEY,
    fk_grupo INTEGER NOT NULL,
    fk_descobridor INTEGER NOT NULL,
    fk_era INTEGER NOT NULL,
    fk_pais INTEGER NOT NULL,
    titulo VARCHAR(256) NOT NULL,
    toneladas INT NOT NULL,
    FOREIGN KEY (fk_grupo) REFERENCES grupo(id),
    FOREIGN KEY (fk_descobridor) REFERENCES DESCOBRIR(id),
    FOREIGN KEY (fk_era) REFERENCES era(id),
    FOREIGN KEY (fk_pais) REFERENCES localizacao(id)
);